### PR TITLE
set config name (required by ehcache > 2.5)

### PR DESCRIPTION
**Pull request by amarkevich**

### CODE REVIEW

**Comment by educhastenier** [comment]
Hi,
Thank you for your participation in making Bonita BPM a better tool.
Can you give some details on the gain of this change, so that it is clear in the commit message?
Thx

**Comment by amarkevich** [comment]
Hi
In my custom connector a CXF Security used which depends on ehcache 2.9. Simple way to have it on classpath is update bonita.war with required version. Unfortunatelly I faced with [1]. All spring configs already have name attribute but there is no support from code.

1. http://stackoverflow.com/questions/10013288/another-unnamed-cachemanager-already-exists-in-the-same-vm-ehcache-2-5

**Comment by ermedeiros** [comment]
Hi,

after applying the changes of your pull request the tests of CommonEhCacheCacheServiceTest are failing. Did you include all necessary changes in the pull request?

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheServiceTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.43 sec <<< FAILURE! - in org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheServiceTest
should_getKeys_return_empty_list_when_cache_manager_have_no_cache(org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheServiceTest)  Time elapsed: 0.026 sec  <<< ERROR!
java.lang.IllegalArgumentException: Cache name cannot be null.
        at net.sf.ehcache.config.CacheConfiguration.setName(CacheConfiguration.java:466)
        at org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheService.getEhCacheConfiguration(CommonEhCacheCacheService.java:70)
        at org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheService.<init>(CommonEhCacheCacheService.java:60)
        at org.bonitasoft.engine.cache.ehcache.EhCacheCacheService.<init>(EhCacheCacheService.java:38)
        at org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheServiceTest$1.<init>(CommonEhCacheCacheServiceTest.java:45)
        at org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheServiceTest.setup(CommonEhCacheCacheServiceTest.java:45)

should_getKeys_return_empty_list_when_cache_manager_is_null(org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheServiceTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.IllegalArgumentException: Cache name cannot be null.
        at net.sf.ehcache.config.CacheConfiguration.setName(CacheConfiguration.java:466)
        at org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheService.getEhCacheConfiguration(CommonEhCacheCacheService.java:70)
        at org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheService.<init>(CommonEhCacheCacheService.java:60)
        at org.bonitasoft.engine.cache.ehcache.EhCacheCacheService.<init>(EhCacheCacheService.java:38)
        at org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheServiceTest$1.<init>(CommonEhCacheCacheServiceTest.java:45)
        at org.bonitasoft.engine.cache.ehcache.CommonEhCacheCacheServiceTest.setup(CommonEhCacheCacheServiceTest.java:45)
```

**Comment by amarkevich** [comment]
updated

**Comment by educhastenier** [comment]
Closing this PR, as:
* structure of the project has changed
* will fix it with different approach

**Pull request closed without merging**
