### PR TITLE
BS-14904 - Upgrade commons-collections version to 3.2.2

### PR DESCRIPTION
**Pull request by abirembaut**
see https://issues.apache.org/jira/browse/COLLECTIONS-580

### CODE REVIEW

**Comment by educhastenier** [comment]
maybe we could build Engine artefacts and check dependency:tree to be sure *commons-collections* is in version 3.2.2

**Comment by abirembaut** [comment]
@educhastenier I did it and couldn't find any other version (there is commons-collections4, but its classes are in a different package and both version can live together in the classpath)

**Comment by educhastenier** [comment]
Perfect, I did ask for more :+1:  !

**Comment by abirembaut** [comment]
related to bonitasoft/bonita-web/pull/224

**Pull request merged**
