### PR TITLE
Close FileOutputStream after file copy in platform setup pull operation

### PR DESCRIPTION
**Pull request by jventrib**
When using platform setup from inside the server JVM (with PlatformSetupAccessor from a JMX mbean for exemple), if we do two consecutives pull operation calls, the second one is failing during initial directory cleanup.
The cause is the FileoutputStream for each file is not closed after being written, so the files are not released.

### CODE REVIEW

**Comment by tbouffard** [comment]
Hi @jventrib 
thanks for this Pull Request. Can you please sign the CLA? This will allow us to use your code as part of the product.

**Comment by educhastenier** [comment]
Hi @jventrib,
Nice catch. We'd be happy to integrate your suggestion.
Would you mind signing the [Licence CLA](https://cla-assistant.io/bonitasoft/bonita-engine?pullRequest=267), so that we can merge your pull request?
Thanks in advance.

**Comment by jventrib** [comment]
Hello,

Sorry for the delay. I've just signed the CLA !
Regards

**Comment by tbouffard** [comment]
@jventrib no problem
We are going to review your pull request. We should be able to integrate it in the 7.6.1 version

**Comment by educhastenier** [comment]
Hi,
I'm sorry, when experimenting some tooling on Github, it accidentally closed your Pull Request.
If you're ok with that, I will recreate the PR with your commit, once I fixed the Github tooling I'm working on.
Thanks for your comprehension.

**Comment by jventrib** [comment]
Hello,

Sure, no problem.

**Comment by tbouffard** [comment]
Hi @jventrib 
This bug is tracked internally with BS-17514 (private issue tracker)
I should be able to work on it soon and I hope to integrate the fix in the upcoming 7.6.3 release.

I will keep you inform when this is done

**Comment by tbouffard** [comment]
Hello @jventrib 
your contribution has been integrated and will be available in the upcoming 7.7.0 version
See commit f048beb6ebf56d5c2f95af7f14a9af1149173dae

**Pull request closed without merging**
