### PR TITLE
Feat/EB-51 correct tests

### PR DESCRIPTION
**Pull request by guillaumerosinosky**
Correction on some tests:
- string values passed instead of integers in some tests made them fail on db2 & derby (as they are more strong typed on strings than other vendors)
- better utf8 tests (they could not pass in db2 as it uses byte sized varchars, and some tests used vanilla ascii characters instead of utf8)

PR previously done on MBF now on master.

### CODE REVIEW

**Comment by educhastenier** [comment]
test RoleIT.roleNameAndDisplayNameShouldAccept255Chars() fails on **H2** because value too large for column.
Can you fix it?

**Comment by educhastenier** [comment]
On **MySQL** also, by the way

**Comment by guillaumerosinosky** [comment]
I look this soon. It's weird, because the total of characters tested here is really 255 (with two 4 octets utf8 characters).

**Comment by guillaumerosinosky** [comment]
Done. As some databases can't manage 4 bytes utf8 characters without tuning (see https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html ), i have put a 255x 3 bytes characters string for the test.

**Pull request closed without merging**
